apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  application.yml: |-
    induction-extension:
      periods:
{{ toYaml .Values.inductionExtension.periods | indent 8 }}