apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hmpps-education-and-work-plan-api" . }}-config
data:
  application.yml: |
    induction-extension:
      periods:
{{- range .Values.config.inductionExtension.periods }}
        - start: {{ .start }}
          end: {{ .end }}
{{- end }}