apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hmpps-education-and-work-plan-api.fullname" . }}-config
data:
  application.yml: |-
    induction-extension:
      periods:
{{ toYaml .Values.inductionExtension.periods | indent 8 }}